---
AWSTemplateFormatVersion: 2010-09-09
Description: Backup for S3 buckets
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: io
Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Sub ${ProjectName}-s3-backup-vault
      AccessPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: '*'
            Action:
              - backup:DeleteBackupVault
              - backup:DeleteBackupVaultAccessPolicy
              - backup:DeleteRecoveryPoint
              - backup:StartCopyJob
              - backup:StartRestoreJob
              - backup:UpdateRecoveryPointLifecycle
            Resource: '*'
      BackupVaultTags:
        Name: !Sub ${ProjectName}-s3-backup-vault
        ProjectName: !Ref ProjectName
  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Sub ${ProjectName}-s3-backup-plan
        BackupPlanRule:
          - RuleName: !Sub ${ProjectName}-s3-backup-rule
            TargetBackupVault: !Ref BackupVault
            EnableContinuousBackup: true
            ScheduleExpression: cron(0 5 * * ? *)
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 35
      BackupPlanTags:
        Name: !Sub ${ProjectName}-s3-backup-plan
        ProjectName: !Ref ProjectName
  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: !Sub ${ProjectName}-s3-backup-selection
        IamRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/backup.amazonaws.com/AWSServiceRoleForBackup
        Resources:
          - !Sub arn:aws:s3:::*
        # ListOfTags:
        #   - ConditionKey: ProjectName
        #     ConditionType: STRINGEQUALS
        #     ConditionValue: !Ref ProjectName
        Conditions:
          StringEquals:
            - ConditionKey: aws:ResourceTag/ProjectName
              ConditionValue: !Ref ProjectName
Outputs:
  BackupVault:
    Value: !Ref BackupVault
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BackupVault
  BackupPlan:
    Value: !Ref BackupPlan
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BackupPlan
  BackupSelection:
    Value: !Ref BackupSelection
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BackupSelection
