---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 buckets for I/O
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: io
  EnableS3AccessLogging:
    Description: Enable S3 access logging.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
Conditions:
  CreateAccessLogS3Bucket:
    Fn::Equals:
      - !Ref EnableS3AccessLogging
      - 'true'
Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-input-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      LoggingConfiguration:
        Fn::If:
          - CreateAccessLogS3Bucket
          - DestinationBucketName: !Ref AccessLogS3Bucket
            LogFilePrefix: !Sub ${ProjectName}-input-${AWS::AccountId}/
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-input-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
  ReferenceS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-reference-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      LoggingConfiguration:
        Fn::If:
          - CreateAccessLogS3Bucket
          - DestinationBucketName: !Ref AccessLogS3Bucket
            LogFilePrefix: !Sub ${ProjectName}-reference-${AWS::AccountId}/
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-reference-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
  OutputS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-output-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            # ExpirationInDays: 14
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      LoggingConfiguration:
        Fn::If:
          - CreateAccessLogS3Bucket
          - DestinationBucketName: !Ref AccessLogS3Bucket
            LogFilePrefix: !Sub ${ProjectName}-output-${AWS::AccountId}/
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-output-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
  ArchiveS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-archive-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Glacier-Instant-Retrieval-after-14day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
              - TransitionInDays: 14
                StorageClass: GLACIER_IR
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      LoggingConfiguration:
        Fn::If:
          - CreateAccessLogS3Bucket
          - DestinationBucketName: !Ref AccessLogS3Bucket
            LogFilePrefix: !Sub ${ProjectName}-archive-${AWS::AccountId}/
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-archive-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
  AccessLogS3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateAccessLogS3Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-log-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-log-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
Outputs:
  InputS3Bucket:
    Value: !Ref InputS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-InputS3Bucket
  ReferenceS3Bucket:
    Value: !Ref ReferenceS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ReferenceS3Bucket
  OutputS3Bucket:
    Value: !Ref OutputS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-OutputS3Bucket
  ArchiveS3Bucket:
    Value: !Ref ArchiveS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ArchiveS3Bucket
  AccessLogS3Bucket:
    Value:
      Fn::If:
        - CreateAccessLogS3Bucket
        - !Ref AccessLogS3Bucket
        - 'null'
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AccessLogS3Bucket
